				<p id="footer">This web page is maintained by informaticians within <a href="http://www.csiro.au/en/Research/LWF">CSIRO Land &amp; Water</a>. See <a href="/about">About</a> for more info.</p>
			</div><!-- #ontainer-content-2 -->
        </div><!-- #ontainer-content -->
	<div id="footer-external">
		<ul id="footer-external-links">
	        	<li>CSIRO links: </li>
		        <li><a href="http://www.csiro.au/Copyright.aspx">Copyright</a></li>
		        <li>|</li>
		        <li><a href="http://www.csiro.au/Legal-Notice-and-Disclaimer.aspx">Legal Notice and Disclaimer</a></li>
		        <li>|</li>
		        <li><a href="http://www.csiro.au/Privacy.aspx">Privacy</a></li>
		        <li>|</li>
		        <li><a href="http://www.csiro.au/Accessibility.aspx">Accessibility</a></li>
		        <li>|</li>
		        <li class="last"><a href="http://www.csiro.au/Sitemap.aspx">Site Map</a></li>
		</ul>
	</div><!-- footer external -->
    </body>
</html>
